### ISSUE TITLE
很方便很好用，但是cookie可以持久化吗？

### ISSUE THREAD

**Issue by alpha87** [v2018z/studyxixi#6]
首先感谢作者提供的软件！

可以实现把cookie储存起来，可以定期更新而不是每次都扫码吗？感觉每次扫码都有些麻烦。

谢谢🙏

**Comment by v2018z** [comment]
强国登录是根据token来的，token的失效时机由服务端控制。所谓cookie记录这一步强国本来就有做，如果你长期没有再使用强国，强国就会把你踢粗去。可以使用最新版本，不要关闭软件，不出意外每隔六个小时保活

**Comment by alpha87** [comment]
明白了，谢谢！

再次感谢这么好用的软件！
