### ISSUE TITLE
已解决，感谢大神

### ISSUE THREAD

**Issue by 84024257** [v2018z/studyxixi#9]
已解决，感谢大神

**Comment by 84024257** [comment]
完成

**Comment by magicyudong** [comment]
怎么解决的，目前还有00007b报错

**Comment by magicyudong** [comment]
兄弟，能发个可执行的exe文件吗







| |
宣玉栋
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月5日 14:32 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [v2018z/studyxixi] 已解决，感谢大神 (Issue #9) |

怎么解决的，目前还有00007b报错

没有遇到,只是打包打不了，编译过了就直接运行
cnpm install
cnpm run build
electron ./dist/main.js

**Comment by 84024257** [comment]
不得行，环境整了半天也还是有点问题，打不了包，我是源码运行的，但是好像也没有分数....等等作者吧....

**Comment by v2018z** [comment]
解决了，在仓库重新下载使用看看发自我的 iPhone在 2024年3月5日，10:39，magicyudong ***@***.***> 写道：﻿
怎么解决的，目前还有00007b报错

**Comment by v2018z** [comment]
解决了，仓库下载试试看发自我的 iPhone在 2024年3月5日，14:32，Chris ***@***.***> 写道：﻿

怎么解决的，目前还有00007b报错

没有遇到,只是打包打不了，编译过了就直接运行
cnpm install
cnpm run build
electron ./dist/main.js

**Comment by magicyudong** [comment]
大神优秀啊
